
on: [push]

name: build

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Install packages
        run: sudo apt-get install -y musl-dev ninja-build clang-13 libsdl2-dev libsigsegv-dev

      - name: Make
        run: make functions examples testsuites

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: test

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
